### PR TITLE
Client pyinstaller

### PR DESCRIPTION
**Pull request by nickdelgrosso**
Hi,

This pull request builds on the pyinstaller client work from the coding club session.  Unfortunatly, it still doesn't work--for some reason, there's a hidden import in Bento that uses cattrs that doesn't seem to be going properly into the pyinstaller distribution.  Error below:

```
  File "dcp_client/main_window.py", line 4, in <module>
    from bentoml.client import Client
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "bentoml/__init__.py", line 25, in <module>
  File "bentoml/_internal/configuration/__init__.py", line 137, in load_config
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "bentoml/_internal/configuration/containers.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "bentoml/_internal/utils/__init__.py", line 33, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "bentoml/_internal/utils/cattr.py", line 12, in <module>
  File "bentoml/_internal/utils/pkg.py", line 32, in pkg_version_info
  File "importlib/metadata.py", line 569, in version
  File "importlib/metadata.py", line 542, in distribution
  File "importlib/metadata.py", line 196, in from_name
importlib.metadata.PackageNotFoundError: cattrs
[121891] Failed to execute script 'run_client' due to unhandled exception!
```

Best wishes,

Nick

### CODE REVIEW

**Review by donatella-cea — COMMENTED** [review]
@nickdelgrosso Did you try adding this to the command line?
```--copy-metadata cattrs```

**Comment by christinab12** [comment]
let's try and get this working before we merge!

**Comment by hpelin** [comment]
Status: Keeping this pull request open for now until we figure out the errors.

**Comment by christinab12** [comment]
Hi,

did we get this working?

**Comment by nickdelgrosso** [comment]
Oh, I was just closing the pull request as being stale.

**Pull request closed without merging**
